### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Al2Klimov** [Nurmukhamed/centos-7-build-asterisk-rpms#2]

**Comment by Nurmukhamed** [comment]
Sorry for late reply.
so i need to do?

**Comment by Al2Klimov** [comment]
Hello @Nurmukhamed,

I asked you for adding the license for all the files in this repository because my employer wants to provide Asterisk packages to a customer, but we'd like to see some kind of **terms of use** (GPLv2+ / BSD3 / whatever) and a **full list of authors** (you, me and all the guys from "mostly borrowed from https://github.com/pld-linux/asterisk/ ...") before we **distribute** 3rd party stuff **commercially**.

I couldn't find the license of https://github.com/pld-linux/asterisk/. If I did, I had already opened a pull request so you could just merge it.

(The license would affect my changes as well, but I don't mind wich one it is as long as it's not "all rights reserved" or BSD4 or similar.)

@Jajcus seems to be the biggest contributor of the repo you forked this from. I think I gonna ask him...

Best,
AK

**Comment by Jajcus** [comment]
Hello @Nurmukhamed,

I think all our (PLD Linux) spec files and patches are supposed to be licensed under GNU GPL v2+ , but I cannot find any official confirmation. I have asked our team, so I can have a better answer soon.

Jacek

**Comment by Al2Klimov** [comment]
Hello @Jajcus,

thx for your investigations.

Once you provided a better answer, I'm gonna do all the donkeywork. (Open a pull request at your repo with license and authors list.) OK?

Anyway this repo will be the next one so you – @Nurmukhamed – won't have to do anything (basically).

Best,
AK

**Comment by Jajcus** [comment]
I remembered correctly – our spec and patch files are licensed GPL v2.
The COPYING file was lost long time ago during migration from CVS to GIT, but it is still there in the old repo:

http://cvs.pld-linux.org/cgi-bin/viewvc.cgi/cvs/SPECS.old/COPYING?view=markup
http://cvs.pld-linux.org/cgi-bin/viewvc.cgi/cvs/packages/COPYING?view=markup

**Comment by Al2Klimov** [comment]
Ladies an gentlemen, welcome *the donkeywork*: https://github.com/pld-linux/asterisk/pull/1
